server:
  port: 8090

spring:
  datasource:
    url: jdbc:h2:tcp://localhost/~/s3
    username: sa
    password:
    driver-class-name: org.h2.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        format_sql : true


